### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TulgaCG** [TulgaCG/add-drop-classes-api#18]
# TODO: 
### Need to rewrite handlers with new permissions middleware:
- [x] rewrite `user.GetHandler`
- [x] rewrite `user.UpdateHandler`
- [x] rewrite `lecture.GetFromUserHandler`
- [x] rewrite `lecture.AddToUserHandler`
- [x] rewrite `lecture.RemoveFromUserHandler`
